# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    repository.product:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
                - AppBundle\Entity\Product

    repository.configuration:
            class: Doctrine\ORM\EntityRepository
            factory: ["@doctrine.orm.entity_manager", getRepository]
            arguments:
                - AppBundle\Entity\ProductConfiguration

    repository.category:
            class: Doctrine\ORM\EntityRepository
            factory: ["@doctrine.orm.entity_manager", getRepository]
            arguments:
                - AppBundle\Entity\Category

    stylus:
        class: AppBundle\Service\StylusService
        arguments: ['@parser.manager', '@repository.configuration', '@repository.product', '@repository.category']

    parser.manager:
        class: AppBundle\Service\ParserManager
        autowire: true

    perser.config:
        class: AppBundle\Config\PagesConfig
        arguments: [%kernel.root_dir%/config/parser_parameters.yml]


