# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    stylus:
        class: AppBundle\Service\StylusService
        autowire: true

    product_container:
        class: AppBundle\Service\ParserContainer
        autowire: true

    product_params:
        class: AppBundle\Config\PagesParams


